# Generated by Django 2.2.7 on 2019-11-08 02:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('goalkeeper', '0006_auto_20191108_0227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='created_at',
            field=models.DateField(verbose_name=datetime.datetime(2019, 11, 8, 2, 29, 17, 717493, tzinfo=utc)),
        ),
    ]
