# Generated by Django 2.2.7 on 2019-11-08 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goalkeeper', '0011_goal_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='numeric_goal',
            field=models.PositiveIntegerField(),
        ),
    ]
