# Generated by Django 2.2.7 on 2019-11-08 22:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goalkeeper', '0012_auto_20191108_2213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='day',
        ),
        migrations.AddField(
            model_name='history',
            name='day_of_input',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='goal',
            name='created_at',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='history',
            name='daily_input',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='history',
            name='target',
            field=models.PositiveIntegerField(),
        ),
    ]
