# Generated by Django 2.2.7 on 2019-11-09 00:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goalkeeper', '0014_auto_20191108_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='operator',
            field=models.CharField(choices=[('<', 'fewer than'), ('>', 'more than'), ('>=', 'at least'), ('<=', 'at most'), ('=', 'exactly')], max_length=10),
        ),
        migrations.AlterField(
            model_name='goal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL),
        ),
    ]
