# Generated by Django 2.2.7 on 2019-11-09 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goalkeeper', '0016_auto_20191109_0205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='operator',
            field=models.CharField(choices=[('fewer than', 'fewer than'), ('more than', 'more than'), ('at least', 'at least'), ('at most', 'at most'), ('exactly', 'exactly')], max_length=10),
        ),
    ]
